### ISSUE TITLE
Require doesn't seem to be working

### ISSUE THREAD

**Issue by gabrielecirulli** [browserify-rails/browserify-rails#27]
I'm trying to use non-string literal requires in my code. I've added `config/browserify.yml`:

```
javascript:
  application:
    require:
      - routes/route_a/sub_route.js
```

In my codebase, I have a file called `application.js` which requires a file called `router.js`. This file, in turn, contains calls to `require` looped over a list of available routes.

Since in Browserify, `require` won't work with anything except a string literal, this means I need to somehow make it aware that these files exist, and as far as I know that should be possible using the `--require` option.

Judging from the output in my console, `browserify-rails` doesn't seem to pass the `--require` argument at all when compiling my code.

Is there something wrong in the way I'm doing this, or is it not working correctly?

---

In the end (if this issue gets resolved), I would like to end up with something like:

```
javascript:
  application:
    require:
      - routes/**/*.js
```

This is because I'd like to avoid having to specify every single script that's present in my routes tree here. Is that possible?
