### ISSUE TITLE
Trouble with multiple bundles

### ISSUE THREAD

**Issue by tylerball** [browserify-rails/browserify-rails#6]
I'm having trouble creating a multiple bundle setup.

Here's my `config/browserify.yml`:

```
javascript:
  application:
    require:
      - jquery
      - lodash
  pages/online:
    external:
      - jquery
      - lodash
```

Using a `require('jquery')` inside of `pages/online.js` gives the following error:

```
 Uncaught Error: Cannot find module 'tpyseH'
```
